# Generated by Django 5.0.6 on 2024-05-25 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refugioPerro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perro',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='perro',
            name='id_refugio',
        ),
    ]
